### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [dead8309/Kizzy#261]
My scanner just reported:

```
! repo/com.my.kizzy_6.apk declares sensitive permission(s):
  android.permission.QUERY_ALL_PACKAGES android.permission.READ_EXTERNAL_STORAGE
! repo/com.my.kizzy_6.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Could you please clarify what those permissions are required for? I guess `QUERY_ALL_PACKAGES` is needed for the app detection feature. But what are the read/write storage permissions for? While on it, in case you wish to fill (some of) the other gaps as well:

![image](https://github.com/dead8309/Kizzy/assets/6781438/15351421-bb6d-4690-a61d-b1eedf5b2cf2)

As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks in advance!

**Comment by dead8309** [comment]
Thanks for writing this issue up!

yes the ` QUERY_ALL_PACKAGES` is necessary for reading all the apps to be shown in Apps Rpc screen and also to get the current running app information like icon, name etc from package manager

`READ/WRITE_EXTERNAL_STORAGE`  so users can save their custom configs in their external storage although its disabled from android13+

`MEDIA_CONTENT_CONTROL` is for extracting currently playing media information from notifications

didn't knew about `DEPENDENCY_INFO_BLOCK` thing sure ill add it.

**Comment by dead8309** [comment]
I'll just reopen it incase you need more details

**Comment by IzzySoft** [comment]
Thanks for all the details, @dead8309! So this is what it looks now:

![image](https://github.com/dead8309/Kizzy/assets/6781438/b9c0ebce-3ed9-4afd-8fb7-ce61c22c9411)

Maybe we can fill the `PACKAGE_USAGE_STATS` as well? The collection of foreground service, wakelock, and battery optimizations certainly is so the app can update its details even when backgrounded, and I guess `POST_NOTIFICATIONS` goes into the same category for a "permanent notification" or such? I might add that as well for those not getting the connection, as many permissions are rather techy for those not digging into all this.

**Comment by dead8309** [comment]
> Maybe we can fill the `PACKAGE_USAGE_STATS`

Oh it's for allowing app the Usage Access permission so it can use the UsageStatsManager to get the last run  app

**Comment by dead8309** [comment]
I was wondering why didn't your script caught all these things earlier. 

Is that because this release had the increment (#229 ) in version code which caught your script eyes or some internal change

**Comment by IzzySoft** [comment]
> Oh it's for allowing app the Usage Access permission so it can use the UsageStatsManager to get the last run app

Thanks, added!

> I was wondering why didn't your scanner caught all these things earlier.

Maybe also because those updates to my scanner only happened in February – and this was your first release after that?

**Comment by dead8309** [comment]
> Maybe also because those updates to my scanner only happened in February – and this was your first release after that?

Cool. 

Do you need anything else or should I close it ?

**Comment by IzzySoft** [comment]
Thanks, all questions are answered. Should more come up in the future, I can open a new issue.

**Comment by IzzySoft** [comment]
@dead8309 last release added `android.permission.SYSTEM_ALERT_WINDOW` – could you please clarify what that is needed/used for?

**Comment by dead8309** [comment]
Hi @IzzySoft, It's used to show the alert dialog on the lock screen when used clicks on the quick settings tile

**Comment by IzzySoft** [comment]
Thanks @dead8309 – added to the app's "green list" :smiley:

```yaml
    android.permission.QUERY_ALL_PACKAGES: needed for the app detection feature
    android.permission.PACKAGE_USAGE_STATS: needed to use the UsageStatsManager to get the last run app
    android.permission.READ_EXTERNAL_STORAGE: to read custom configs
    android.permission.WRITE_EXTERNAL_STORAGE: to save custom configs
    android.permission.MEDIA_CONTENT_CONTROL: needed to extract currently playing media information from notifications
    android.permission.SYSTEM_ALERT_WINDOW: used to show the alert dialog on the lock screen when tapping the quick settings tile
```
